# -*- coding: utf-8 -*-
"""Tumor_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0xCXIl3aajkUIFVSKCeOjpiY4nVR8JU

#Install PyTorch
"""

!pip install torch

"""#Import Dependencies"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from PIL import Image

"""#GPU check"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

device

"""#Get the Dataset"""

!pip install kagglehub

import kagglehub

# Download latest version
path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

print("Path to dataset files:", path)

"""#Explore the dataset structure"""

print("Dataset structure:")
for item in os.listdir(path):
    item_path = os.path.join(path, item)
    if os.path.isdir(item_path):
        num_files = sum(len(files) for _, _, files in os.walk(item_path))
        print(f"{item}: {num_files} files")

image_paths = []
labels = []
class_names = []

# The dataset contains Training and Testing folders
for subset in ['Training', 'Testing']:
    subset_dir = os.path.join(path, subset)

    if not os.path.isdir(subset_dir):
        continue

    # Each subset contains class folders
    for class_name in sorted(os.listdir(subset_dir)):
        class_dir = os.path.join(subset_dir, class_name)

        if os.path.isdir(class_dir):
            if class_name not in class_names:
                class_names.append(class_name)

            class_idx = class_names.index(class_name)

            for img_name in os.listdir(class_dir):
                if img_name.endswith(('.jpg', '.jpeg', '.png')):
                    img_path = os.path.join(class_dir, img_name)
                    image_paths.append(img_path)
                    labels.append(class_idx)

# Print dataset statistics
print(f"\nFound {len(image_paths)} images in {len(class_names)} classes")
for i, class_name in enumerate(class_names):
    count = labels.count(i)
    print(f"Class {i} ({class_name}): {count} images")

"""#Create Class for dataset
This cell defines a custom PyTorch Dataset class that:

Takes a list of image paths, labels, and optional transformations
Has a __len__ method to return the total number of images
Has a __getitem__ method to:
1. Load an image from its path
2. Convert it to RGB format (ensuring 3 channels)
3. Apply any specified transformations
4. Return the processed image and its corresponding label

This class will be used to create our training, validation, and test datasets.
"""

class BrainMRIDataset(Dataset):
  def __init__(self, image_paths, labels, transform=None):
    self.image_paths = image_paths
    self.labels = labels
    self.transform = transform

  def __len__(self):
    return len(self.image_paths)

  def __getitem__ (self, idx):
    image_path = self.image_paths[idx]
    image = Image.open(image_path).convert('RGB')
    Label = self.labels[idx]

    if self.transform:
      image = self.transform(image)

    return image, Label

"""#Data Augmentation
This cell defines two sets of image transformations:

Training transformations include data augmentation techniques:

1. Resize all images to 224×224 pixels (standard for many CNN architectures)
2. Random horizontal flips to simulate different orientations
3. Small random rotations (±10 degrees)
4. Small random translations to help model learn position invariance
5. Color jitter to vary brightness and contrast
6. Conversion to tensor
7. Normalization using ImageNet statistics (helps convergence)


Validation/Test transformations are simpler:

1. Only resize, convert to tensor, and normalize
2. No augmentation, as we want consistent evaluation

Data augmentation is crucial for medical image analysis as it helps prevent overfitting and improves the model's ability to generalize by creating variations of the training data.
"""

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

"""#Data validation and train split"""

# Split the dataset into train, validation, and test
test_size = 0.15
val_size = 0.15
seed = 42

# Split the dataset into train+val and test
train_val_paths, test_paths, train_val_labels, test_labels = train_test_split(
    image_paths, labels, test_size=test_size, random_state=seed, stratify=labels
)

# Further split train+val into train and val
train_paths, val_paths, train_labels, val_labels = train_test_split(
    train_val_paths, train_val_labels,
    test_size=val_size/(1-test_size),  # Adjusted validation size
    random_state=seed,
    stratify=train_val_labels
)

train_dataset = BrainMRIDataset(train_paths, train_labels, transform=train_transform)
val_dataset = BrainMRIDataset(val_paths, val_labels, transform=val_test_transform)
test_dataset = BrainMRIDataset(test_paths, test_labels, transform=val_test_transform)

print(f"Training set: {len(train_dataset)} images")
print(f"Validation set: {len(val_dataset)} images")
print(f"Test set: {len(test_dataset)} images")

"""#Create DataLoaders"""

batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Number of training batches: {len(train_loader)}")
print(f"Number of validation batches: {len(val_loader)}")
print(f"Number of test batches: {len(test_loader)}")

"""#Visualize the Data"""

# Function to visualize sample images
def visualize_samples(dataset, class_names, num_samples=5):

    fig, axes = plt.subplots(1, num_samples, figsize=(15, 3))

    for i in range(num_samples):
        # Get a random sample
        idx = np.random.randint(0, len(dataset))
        img, label = dataset[idx]

        # Convert tensor to numpy and denormalize
        if isinstance(img, torch.Tensor):
            img = img.permute(1, 2, 0).numpy()
            # Denormalize the image
            mean = np.array([0.485, 0.456, 0.406])
            std = np.array([0.229, 0.224, 0.225])
            img = std * img + mean
            img = np.clip(img, 0, 1)

        axes[i].imshow(img)
        axes[i].set_title(f"{class_names[label]}")
        axes[i].axis('off')

    plt.tight_layout()
    plt.show()

# Visualize sample images from each dataset
print("Sample images from the training set:")
visualize_samples(train_dataset, class_names, num_samples=5)

print("\nSample images from the validation set:")
visualize_samples(val_dataset, class_names, num_samples=5)

print("\nSample images from the test set:")
visualize_samples(test_dataset, class_names, num_samples=5)

"""# The dataset will be evaluated by two CNN architectures:
1. Custom
2. ResNet

#Custom CNN
"""

class BrainTumorCNN(nn.Module):
    def __init__(self, num_classes=4):
        super(BrainTumorCNN, self).__init__()

        # First convolutional block
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Second convolutional block
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Third convolutional block
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Fourth convolutional block
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool4 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Calculate size after all pooling operations
        # Input: 224x224 -> After 4 pooling layers: 14x14
        self.fc1 = nn.Linear(256 * 14 * 14, 512)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, x):
        # First block
        x = self.conv1(x)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.pool1(x)

        # Second block
        x = self.conv2(x)
        x = self.bn2(x)
        x = F.relu(x)
        x = self.pool2(x)

        # Third block
        x = self.conv3(x)
        x = self.bn3(x)
        x = F.relu(x)
        x = self.pool3(x)

        # Fourth block
        x = self.conv4(x)
        x = self.bn4(x)
        x = F.relu(x)
        x = self.pool4(x)

        # Flatten the output for the fully connected layer
        x = x.view(x.size(0), -1)

        # Fully connected layers
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)

        return x

"""#Model initialization"""

model_cnn = BrainTumorCNN(num_classes=len(class_names))
model_cnn = model_cnn.to(device)

print(model_cnn)
print(f"\nModel moved to: {next(model_cnn.parameters()).device}")

# Calculate total number of parameters
total_params = sum(p.numel() for p in model_cnn.parameters())
print(f"Total parameters: {total_params:,}")
trainable_params = sum(p.numel() for p in model_cnn.parameters() if p.requires_grad)
print(f"Trainable parameters: {trainable_params:,}")

"""#Train and validate functions

This cell:

Sets up the loss function (CrossEntropyLoss) appropriate for multi-class classification
Configures an Adam optimizer with a learning rate of 0.001
Adds a learning rate scheduler that reduces the learning rate when validation loss plateaus
Defines two key functions:

train_epoch: Performs one training epoch with backpropagation
validate: Evaluates the model on validation data without updating weights



The scheduler helps avoid getting stuck in local minima by reducing the learning rate when progress stalls.
"""

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_cnn.parameters(), lr=0.001)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, verbose=True)

# Training and validation functions
def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, labels in dataloader:
        inputs, labels = inputs.to(device), labels.to(device)

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        # Statistics
        running_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total

    return epoch_loss, epoch_acc

def validate(model, dataloader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)

            # Forward pass
            outputs = model(inputs)
            loss = criterion(outputs, labels)

            # Statistics
            running_loss += loss.item() * inputs.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total

    return epoch_loss, epoch_acc

"""#Training Loop"""

num_epochs = 15
best_val_acc = 0.0
history = {
    'train_loss': [], 'train_acc': [],
    'val_loss': [], 'val_acc': []
}

print("Starting training of Custom CNN...")
for epoch in range(num_epochs):
    # Training phase
    train_loss, train_acc = train_epoch(model_cnn, train_loader, criterion, optimizer, device)

    # Validation phase
    val_loss, val_acc = validate(model_cnn, val_loader, criterion, device)

    # Learning rate scheduling
    scheduler.step(val_loss)

    # Save history
    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    # Print statistics
    print(f"Epoch {epoch+1}/{num_epochs}:")
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model_cnn.state_dict(), 'best_custom_cnn_model.pth')
        print(f"Model saved with validation accuracy: {val_acc:.4f}")

    print("-------------------------------")

print(f"Best validation accuracy: {best_val_acc:.4f}")

"""#Test our model"""

# Plot training and validation metrics
plt.figure(figsize=(12, 4))

# Plot loss
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training and Validation Loss')

# Plot accuracy
plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Accuracy')
plt.plot(history['val_acc'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.tight_layout()
plt.show()

# Load the best model for evaluation
model_cnn.load_state_dict(torch.load('best_custom_cnn_model.pth'))
model_cnn.eval()

# Evaluate on test set
test_loss, test_acc = validate(model_cnn, test_loader, criterion, device)
print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_acc:.4f}")

# Calculate per-class accuracy
class_correct = [0] * len(class_names)
class_total = [0] * len(class_names)

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model_cnn(inputs)
        _, predicted = torch.max(outputs, 1)
        c = (predicted == labels).squeeze()

        for i in range(labels.size(0)):
            label = labels[i]
            class_correct[label] += c[i].item()
            class_total[label] += 1

print("\nPer-class Test Accuracy:")
for i in range(len(class_names)):
    accuracy = 100 * class_correct[i] / class_total[i]
    print(f"{class_names[i]}: {accuracy:.2f}%")

import random
import matplotlib.pyplot as plt
import torch
import numpy as np

model_cnn.eval()

def denormalize(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1).to(tensor.device)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1).to(tensor.device)
    return tensor * std + mean

def predict_image(model, image_tensor):
    with torch.no_grad():
        output = model(image_tensor.unsqueeze(0).to(device))
        probabilities = torch.nn.functional.softmax(output, dim=1)
        predicted_class = torch.argmax(output, dim=1).item()
        confidence = probabilities[0][predicted_class].item()

        all_confidences = probabilities[0].cpu().numpy()
    return predicted_class, confidence, all_confidences

num_samples = 5

random_indices = random.sample(range(len(test_dataset)), num_samples)

plt.figure(figsize=(15, 5 * num_samples))

for i, idx in enumerate(random_indices):

    image, true_label = test_dataset[idx]
    image_tensor = image.to(device)

    cnn_pred, cnn_conf, all_confidences = predict_image(model_cnn, image_tensor)

    img_display = denormalize(image_tensor.cpu())
    img_display = img_display.permute(1, 2, 0).numpy()
    img_display = np.clip(img_display, 0, 1)

    plt.subplot(num_samples, 2, 2*i+1)
    plt.imshow(img_display)

    title_color = 'green' if cnn_pred == true_label else 'red'
    title_text = f"True: {class_names[true_label]}\n"
    title_text += f"Pred: {class_names[cnn_pred]} ({cnn_conf:.2f})"

    plt.title(title_text, color=title_color)
    plt.axis('off')

    # Display the confidence bars for all classes
    plt.subplot(num_samples, 2, 2*i+2)
    bars = plt.bar(range(len(class_names)), all_confidences, color='skyblue')

    # Highlight the predicted class
    bars[cnn_pred].set_color('blue')

    # Highlight the true class with an edge
    if cnn_pred != true_label:
        bars[true_label].set_edgecolor('green')
        bars[true_label].set_linewidth(2)

    plt.xticks(range(len(class_names)), class_names, rotation=45)
    plt.ylim(0, 1.0)
    plt.title("Class Confidence Scores")
    plt.tight_layout()

plt.subplots_adjust(hspace=0.5)
plt.tight_layout()
plt.show()

"""#Using ResNet"""

import torchvision.models as models

# Load a pretrained ResNet-50 model
model_resnet = models.resnet50(weights='IMAGENET1K_V2')

num_ftrs = model_resnet.fc.in_features
model_resnet.fc = nn.Linear(num_ftrs, len(class_names))

model_resnet = model_resnet.to(device)

# Print model summary
print(f"ResNet model moved to: {next(model_resnet.parameters()).device}")

for param in model_resnet.parameters():
    param.requires_grad = False

for param in model_resnet.fc.parameters():
    param.requires_grad = True

total_params = sum(p.numel() for p in model_resnet.parameters())
print(f"Total parameters: {total_params:,}")
trainable_params = sum(p.numel() for p in model_resnet.parameters() if p.requires_grad)
print(f"Trainable parameters: {trainable_params:,}")
print(f"Percentage of trainable parameters: {100 * trainable_params / total_params:.2f}%")

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_resnet.fc.parameters(), lr=0.001)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, verbose=True)

"""#Fine tune"""

# Train the ResNet model
num_epochs = 10
best_val_acc = 0.0
history_resnet = {
    'train_loss': [], 'train_acc': [],
    'val_loss': [], 'val_acc': []
}

print("Starting training of ResNet model...")
for epoch in range(num_epochs):
    # Training phase
    train_loss, train_acc = train_epoch(model_resnet, train_loader, criterion, optimizer, device)

    # Validation phase
    val_loss, val_acc = validate(model_resnet, val_loader, criterion, device)

    # Learning rate scheduling
    scheduler.step(val_loss)

    # Save history
    history_resnet['train_loss'].append(train_loss)
    history_resnet['train_acc'].append(train_acc)
    history_resnet['val_loss'].append(val_loss)
    history_resnet['val_acc'].append(val_acc)

    # Print statistics
    print(f"Epoch {epoch+1}/{num_epochs}:")
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model_resnet.state_dict(), 'best_resnet_model.pth')
        print(f"Model saved with validation accuracy: {val_acc:.4f}")

    print("-------------------------------")

print(f"Best validation accuracy: {best_val_acc:.4f}")

"""#Evaluate Model"""

# Plot training and validation metrics for ResNet
plt.figure(figsize=(12, 4))

# Plot loss
plt.subplot(1, 2, 1)
plt.plot(history_resnet['train_loss'], label='Train Loss')
plt.plot(history_resnet['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('ResNet Training and Validation Loss')

# Plot accuracy
plt.subplot(1, 2, 2)
plt.plot(history_resnet['train_acc'], label='Train Accuracy')
plt.plot(history_resnet['val_acc'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('ResNet Training and Validation Accuracy')

plt.tight_layout()
plt.show()

# Load the best ResNet model for evaluation
model_resnet.load_state_dict(torch.load('best_resnet_model.pth'))
model_resnet.eval()

# Evaluate on test set
test_loss, test_acc = validate(model_resnet, test_loader, criterion, device)
print(f"ResNet Test Loss: {test_loss:.4f}, Test Accuracy: {test_acc:.4f}")

# Calculate per-class accuracy for ResNet
class_correct = [0] * len(class_names)
class_total = [0] * len(class_names)

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model_resnet(inputs)
        _, predicted = torch.max(outputs, 1)
        c = (predicted == labels).squeeze()

        for i in range(labels.size(0)):
            label = labels[i]
            class_correct[label] += c[i].item()
            class_total[label] += 1

# Print per-class accuracy
print("\nResNet Per-class Test Accuracy:")
for i in range(len(class_names)):
    accuracy = 100 * class_correct[i] / class_total[i]
    print(f"{class_names[i]}: {accuracy:.2f}%")

import random
import matplotlib.pyplot as plt
import torch
import numpy as np

# Make sure the ResNet model is in evaluation mode
model_resnet.eval()

# Function to denormalize images for display
def denormalize(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1).to(tensor.device)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1).to(tensor.device)
    return tensor * std + mean

def predict_image(model, image_tensor):
    with torch.no_grad():
        output = model(image_tensor.unsqueeze(0).to(device))
        probabilities = torch.nn.functional.softmax(output, dim=1)
        predicted_class = torch.argmax(output, dim=1).item()
        confidence = probabilities[0][predicted_class].item()

        # Also get the confidence values for all classes
        all_confidences = probabilities[0].cpu().numpy()
    return predicted_class, confidence, all_confidences

num_samples = 5

# Get random indices from the test dataset
random_indices = random.sample(range(len(test_dataset)), num_samples)

# Create a figure to display the images and predictions
plt.figure(figsize=(15, 5 * num_samples))

for i, idx in enumerate(random_indices):
    # Get the image and label
    image, true_label = test_dataset[idx]
    image_tensor = image.to(device)

    # Make predictions with the ResNet model
    resnet_pred, resnet_conf, all_confidences = predict_image(model_resnet, image_tensor)

    # Prepare image for display
    img_display = denormalize(image_tensor.cpu())
    img_display = img_display.permute(1, 2, 0).numpy()
    img_display = np.clip(img_display, 0, 1)

    # Display the image with predictions
    plt.subplot(num_samples, 2, 2*i+1)
    plt.imshow(img_display)

    # Set the title with model predictions
    title_color = 'green' if resnet_pred == true_label else 'red'
    title_text = f"True: {class_names[true_label]}\n"
    title_text += f"Pred: {class_names[resnet_pred]} ({resnet_conf:.2f})"

    plt.title(title_text, color=title_color)
    plt.axis('off')

    # Display the confidence bars for all classes
    plt.subplot(num_samples, 2, 2*i+2)
    bars = plt.bar(range(len(class_names)), all_confidences, color='skyblue')

    # Highlight the predicted class
    bars[resnet_pred].set_color('blue')

    # Highlight the true class with an edge
    if resnet_pred != true_label:
        bars[true_label].set_edgecolor('green')
        bars[true_label].set_linewidth(2)

    plt.xticks(range(len(class_names)), class_names, rotation=45)
    plt.ylim(0, 1.0)
    plt.title("Class Confidence Scores")
    plt.tight_layout()

plt.subplots_adjust(hspace=0.5)
plt.tight_layout()
plt.show()